/* 
   STUDENT ASSIGNMENTS PAGE LOGIC
   frontend/student/assignments.js
*/

document.addEventListener('DOMContentLoaded', async () => {
    const user = await requireSession('student').catch(() => null);
    if (!user) return;

    document.querySelector('.avatar').textContent = user.full_name.charAt(0).toUpperCase();
    attachLogout('logout-btn');
    initProfilePopup();

    const groupsEl = document.getElementById('assign-groups');
    const modal = document.getElementById('submit-modal');
    const autoModal = document.getElementById('auto-modal');
    let activeAssignment = null;
    let activeAuto = null;
    let lastAutoGraded = false;

    function escapeHTML(s) {
        return String(s ?? '').replace(/[&<>"']/g, c => ({
            '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
        })[c]);
    }

    // Drop the sidebar badge on the Recommendations link once the auto
    // recommendations have been shown, so it doesn't reappear on refresh.
    function clearRecommendationBadge() {
        const link = document.querySelector('a.nav-link[href*="recommendations.html"]');
        if (link) {
            const badge = link.querySelector('.nav-badge');
            if (badge) badge.remove();
        }
    }

    // Kick off generation of per-student AI assignments for downloaded
    // materials before the list is loaded so fresh ones appear immediately.
    async function ensureAutoGenerated() {
        try {
            const res = await authFetch(`${API_BASE}/api/assignments/auto-generate`, { method: 'POST' });
            if (!res.ok) return 0;
            const data = await res.json();
            if (data.created) {
                invalidateApiCache('assignments');
                invalidateApiCache('assign');
                invalidateApiCache('nav-pending');
            }
            return data.created || 0;
        } catch (err) {
            console.error('Auto-generate failed:', err);
            return 0;
        }
    }

    const statusLabel = (a) => {
        if (a.auto_generated) {
            if (a.submitted) return ['done', 'Completed'];
            return ['pending', 'Take now'];
        }
        if (!a.submitted) {
            const due = a.due_date;
            if (due && String(due).slice(0, 10) < new Date().toISOString().slice(0, 10)) return ['late', 'Overdue'];
            return ['pending', 'Due soon'];
        }
        if (a.on_time) return ['done', 'Submitted'];
        return ['late', 'Submitted late'];
    };

    const closeModal = () => {
        modal.hidden = true;
        activeAssignment = null;
        document.getElementById('submit-content').value = '';
    };

    modal.querySelectorAll('[data-close="true"]').forEach(btn => btn.addEventListener('click', closeModal));
    modal.addEventListener('click', (e) => { if (e.target === modal) closeModal(); });

    function openAuto(assignment, courseTitle) {
        activeAuto = assignment;
        lastAutoGraded = false;
        document.getElementById('auto-title').textContent = assignment.title;
        document.getElementById('auto-sub').textContent = `${courseTitle}${assignment.source_material_title ? ' · Based on: ' + assignment.source_material_title : ''}`;
        document.getElementById('auto-instructions').textContent = assignment.instructions || 'Answer the questions based on the material you downloaded. Objective questions are scored automatically; theory answers are graded by AI.';
        const questions = assignment.questions || {};
        const objHtml = (questions.objective || []).map((q, i) => `
            <div class="auto-question">
                <p class="auto-q-label">Objective ${i + 1}</p>
                <p class="auto-q-text">${escapeHTML(q.question)}</p>
                <div class="auto-options">
                    ${(q.options || []).map((opt, oi) => `
                        <label class="auto-option">
                            <input type="radio" name="obj-${i}" value="${oi}">
                            <span>${escapeHTML(opt)}</span>
                        </label>`).join('')}
                </div>
            </div>`).join('');
        const theoryHtml = (questions.theory || []).map((q, i) => `
            <div class="auto-question">
                <p class="auto-q-label">Theory ${i + 1}</p>
                <p class="auto-q-text">${escapeHTML(q.question)}</p>
                <textarea class="auto-theory-input" rows="4" placeholder="Type your answer..."></textarea>
            </div>`).join('');
        document.getElementById('auto-questions').innerHTML = objHtml + theoryHtml;
        document.getElementById('auto-submit-btn').style.display = '';
        document.getElementById('auto-cancel-btn').textContent = 'Cancel';
        autoModal.hidden = false;
    }

    async function submitAuto() {
        if (!activeAuto) return;
        const btn = document.getElementById('auto-submit-btn');
        btn.disabled = true;
        try {
            const questions = activeAuto.questions || {};
            const objective = (questions.objective || []).map((q, i) => {
                const sel = document.querySelector(`input[name="obj-${i}"]:checked`);
                return sel ? parseInt(sel.value, 10) : -1;
            });
            if (objective.some(v => v === -1)) {
                showToast('Answer all objective questions before submitting.', 'error');
                btn.disabled = false;
                return;
            }
            const theory = [];
            document.querySelectorAll('.auto-theory-input').forEach(t => theory.push(t.value.trim()));
            const res = await authFetch(`${API_BASE}/api/assignments/submit`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ assignment_id: activeAuto.id, content: '', answers: { objective, theory } }),
            });
            const data = await res.json().catch(() => ({}));
            if (res.ok) {
                lastAutoGraded = true;
                invalidateApiCache('assignments');
                invalidateApiCache('assign');
                invalidateApiCache('stats');
                invalidateApiCache('study-summary');
                invalidateApiCache('nav-pending');
                invalidateApiCache('nav-stats');
                const recs = data.recommendations || [];
                const recsHtml = recs.length ? `
                    <div class="auto-recs">
                        <h4 class="auto-recs-title"><i class="bi bi-stars"></i> Recommended for you</h4>
                        <p class="auto-recs-note">Your score was below 60% — these resources can help you improve.</p>
                        <ul class="auto-recs-list">
                            ${recs.map(r => {
                                const src = r.resource_source || 'resource';
                                const srcLabel = { material: 'Course Material', youtube: 'YouTube', article: 'Article' }[src] || src;
                                const href = r.resource_url
                                    ? ` href="${escapeHTML(r.resource_url)}" target="_blank" rel="noopener noreferrer"`
                                    : '';
                                return `
                                    <li class="auto-recs-item">
                                        <span class="auto-recs-src">${escapeHTML(srcLabel)}</span>
                                        ${href
                                            ? `<a class="auto-recs-link"${href}>${escapeHTML(r.resource_title || 'View resource')}</a>`
                                            : `<span class="auto-recs-link">${escapeHTML(r.resource_title || 'Course material')}</span>`}
                                        ${r.resource_description ? `<p class="auto-recs-desc">${escapeHTML(r.resource_description)}</p>` : ''}
                                    </li>`;
                            }).join('')}
                        </ul>
                    </div>` : '';
                document.getElementById('auto-questions').innerHTML = `
                    <div class="auto-result">
                        <div class="auto-result-score">${data.score}%</div>
                        <div class="auto-result-grade">Grade: ${data.letter_grade}</div>
                        <p class="auto-result-feedback">${escapeHTML(data.feedback || '')}</p>
                    </div>
                    ${recsHtml}`;
                document.getElementById('auto-submit-btn').style.display = 'none';
                document.getElementById('auto-cancel-btn').textContent = 'Close';
                if (recs.length) {
                    clearRecommendationBadge();
                    authFetch(`${API_BASE}/api/recommendations/notifications/read`, { method: 'POST' }).catch(() => {});
                }
            } else {
                showToast(data.detail || 'Could not submit your assignment.', 'error');
            }
        } catch (err) {
            showToast('Could not submit your assignment.', 'error');
        } finally {
            btn.disabled = false;
        }
    }

    function closeAutoModal() {
        autoModal.hidden = true;
        if (lastAutoGraded) loadAssignments();
        activeAuto = null;
    }
    document.getElementById('auto-submit-btn').addEventListener('click', submitAuto);
    autoModal.querySelectorAll('[data-auto-close="true"]').forEach(btn => btn.addEventListener('click', closeAutoModal));
    autoModal.addEventListener('click', (e) => { if (e.target === autoModal) closeAutoModal(); });

    function openSubmit(assignment, courseTitle) {
        activeAssignment = assignment;
        document.getElementById('modal-title').textContent = assignment.title;
        document.getElementById('modal-assignment').textContent = `${courseTitle} · Due ${assignment.due_date || 'no fixed date'}`;
        modal.hidden = false;
        document.getElementById('submit-content').focus();
    }

    async function submitActive() {
        const content = document.getElementById('submit-content').value;
        if (!content.trim()) {
            showToast('Write your answer before submitting.', 'error');
            return;
        }
        const btn = document.getElementById('submit-btn');
        btn.disabled = true;
        try {
            const res = await authFetch(`${API_BASE}/api/assignments/submit`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ assignment_id: activeAssignment.id, content }),
            });
            const data = await res.json().catch(() => ({}));
            if (res.ok) {
                showToast(data.on_time ? 'Assignment submitted on time.' : 'Assignment submitted late.', 'success');
                invalidateApiCache('assignments');
                invalidateApiCache('assign');
                invalidateApiCache('stats');
                invalidateApiCache('study-summary');
                invalidateApiCache('nav-pending');
                invalidateApiCache('nav-stats');
                closeModal();
                loadAssignments();
            } else {
                showToast(data.detail || 'Could not submit your assignment.', 'error');
            }
        } catch (err) {
            showToast('Could not submit your assignment.', 'error');
        } finally {
            btn.disabled = false;
        }
    }
    document.getElementById('submit-btn').addEventListener('click', submitActive);

    function renderAssignmentGroups(groups) {
        let dueSoon = 0, done = 0, late = 0;

        groups.forEach(({ assignments }) => {
            assignments.forEach(a => {
                const [cls] = statusLabel(a);
                if (cls === 'done') done++;
                else if (cls === 'late') late++;
                else dueSoon++;
            });
        });

        if (!groups.length) {
            groupsEl.innerHTML = '<div class="empty-state">No assignments yet. Download a course material to unlock your AI-generated assignment.</div>';
        } else {
            groupsEl.innerHTML = groups.map(({ course, assignments }, gi) => `
                    <div class="assign-group" style="animation-delay: ${gi * 80}ms">
                        <div class="group-head">
                            <h3>${course.title}</h3>
                            <span class="group-count">${assignments.length} assignment${assignments.length === 1 ? '' : 's'}</span>
                        </div>
                        ${assignments.length ? assignments.map(a => {
                            const [cls, label] = statusLabel(a);
                            const gradeChip = a.auto_generated && a.submitted
                                ? `<div class="auto-grade">
                                        <span class="auto-grade-score">${a.score}%</span>
                                        <span class="assign-status done">${a.letter_grade}</span>
                                  </div>`
                                : '';
                            const feedbackSnippet = a.auto_generated && a.feedback
                                ? `<p class="auto-feedback">${escapeHTML(a.feedback)}</p>`
                                : '';
                            return `
                            <div class="assign-item${a.auto_generated ? ' assign-item-auto' : ''}">
                                <div class="assign-item-head">
                                    <h4>${a.title} ${a.auto_generated ? '<span class="auto-badge">Auto</span>' : ''}</h4>
                                    <span class="assign-status ${cls}">${label}</span>
                                </div>
                                <div class="assign-meta">
                                    <span>${a.auto_generated ? 'From your downloads' : 'Week ' + (a.week_number || '–')}</span>
                                    <span>${a.auto_generated ? (a.submitted ? 'Graded' : 'No due date') : 'Due ' + (a.due_date || 'flexible')}</span>
                                </div>
                                ${a.auto_generated && a.submitted ? gradeChip + feedbackSnippet : ''}
                                ${!a.auto_generated && a.instructions ? `<p class="assign-instructions">${a.instructions}</p>` : ''}
                                <div class="assign-actions">
                                    ${a.auto_generated
                                        ? (a.submitted
                                            ? `<span class="assign-status ${cls}">${a.on_time ? 'Graded' : 'Completed'}</span>`
                                            : `<button class="btn-submit" data-auto-id="${a.id}" data-course="${course.title}">Take assignment</button>`)
                                        : (a.submitted
                                            ? `<span class="assign-status ${cls}">${a.on_time ? 'On time' : 'Late'}</span>`
                                            : `<button class="btn-submit" data-assign-id="${a.id}" data-course="${course.title}">Submit assignment</button>`)}
                                </div>
                            </div>`;
                        }).join('') : `
                        <div class="assign-unlock">
                            <div class="assign-unlock-text">
                                <h4>Download material to unlock your assignment</h4>
                                <p>No assignment yet — download this course's material and an AI assignment will be generated for you.</p>
                            </div>
                            <a class="btn-submit" href="../materials/materials.html?id=${course.id}">Download material</a>
                        </div>`}
                    </div>
                `).join('');

                groupsEl.querySelectorAll('.btn-submit').forEach(btn => {
                    btn.addEventListener('click', () => {
                        const id = btn.dataset.assignId;
                        const autoId = btn.dataset.autoId;
                        const course = btn.dataset.course;
                        const item = groups.flatMap(g => g.assignments).find(a => a.id === (id || autoId));
                        if (!item) return;
                        if (autoId) openAuto(item, course);
                        else openSubmit(item, course);
                    });
                });
            }

        document.getElementById('due-count').textContent = dueSoon;
        document.getElementById('done-count').textContent = done;
        document.getElementById('late-count').textContent = late;
    }

    async function loadAssignments() {
        // Paint the persisted view instantly; the network only runs after a
        // mutation, an F5 reload, or once the cache ages past the TTL.
        const cachedGroups = cachedRead('assignments');
        if (cachedGroups) renderAssignmentGroups(cachedGroups);

        try {
            const courses = await swrGet('my-courses', `${API_BASE}/api/students/${user.id}/courses`);

            if (!courses.length) {
                if (!cachedGroups) {
                    groupsEl.innerHTML = '<div class="empty-state">You are not enrolled in any courses yet. <a href="../courses/courses.html">Browse courses</a></div>';
                }
                return;
            }

            const loadOne = async (course) => {
                try {
                    const data = await swrGet(`assign:${course.id}`, `${API_BASE}/api/assignments/course/${course.id}`);
                    return { course, assignments: data.assignments || [] };
                } catch (err) {
                    return null;
                }
            };

            const results = (await Promise.all(courses.map(loadOne))).filter(Boolean);
            cachedWrite('assignments', results);
            renderAssignmentGroups(results);
        } catch (err) {
            console.error('Error loading assignments:', err);
            if (!cachedGroups) {
                groupsEl.innerHTML = '<div class="empty-state">Unable to load assignments. Please try again later.</div>';
                showToast('Unable to load assignments.', 'error');
            }
        }
    }

    // Don't block the list on AI auto-generation: render what's there now, and
    // reload once generation finishes if it actually created new assignments.
    const genPromise = ensureAutoGenerated();
    loadAssignments();
    const created = await genPromise;
    if (created > 0) loadAssignments();
});
