-- Migration: 20260813000017_progress_assignments.sql
-- Adds:
--  1. week_number to materials (weekly material organisation)
--  2. Telemetry columns back onto engagement_logs (dropped in 00010) so the
--     /api/engagement/log endpoint can persist study time for warnings.
--  3. assignments + assignment_submissions (on-time submission tracking)
--  4. study_resources (lecturer AI-generated study guides from course content)

-- ── 1. Weekly materials organisation ─────────────────────────────────────────
ALTER TABLE materials ADD COLUMN IF NOT EXISTS week_number INTEGER;
CREATE INDEX IF NOT EXISTS idx_materials_course_week ON materials(course_id, week_number);

-- ── 2. Engagement telemetry columns (restore) ────────────────────────────────
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS mouse_movements INTEGER DEFAULT 0;
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS scroll_depth INTEGER DEFAULT 0;
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS clicks INTEGER DEFAULT 0;
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS time_spent INTEGER DEFAULT 0;
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS idle_time INTEGER DEFAULT 0;
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS engagement_score FLOAT;
ALTER TABLE engagement_logs ADD COLUMN IF NOT EXISTS engagement_level TEXT;

-- ── 3. Assignments ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS assignments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    instructions TEXT,
    due_date DATE,
    week_number INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_assignments_course ON assignments(course_id);
CREATE INDEX IF NOT EXISTS idx_assignments_due ON assignments(due_date);

CREATE TABLE IF NOT EXISTS assignment_submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    assignment_id UUID NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (assignment_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_submissions_assignment ON assignment_submissions(assignment_id);
CREATE INDEX IF NOT EXISTS idx_submissions_student ON assignment_submissions(student_id);

ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignment_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "everyone_view_assignments" ON assignments
    FOR SELECT USING (true);
CREATE POLICY "service_role_assignments" ON assignments
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "students_view_own_assignment_submissions" ON assignment_submissions
    FOR SELECT USING (student_id = auth.uid());
CREATE POLICY "students_insert_own_assignment_submissions" ON assignment_submissions
    FOR INSERT WITH CHECK (student_id = auth.uid());
CREATE POLICY "service_role_assignment_submissions" ON assignment_submissions
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── 4. Study resources (AI-generated by lecturers from course content) ──────
CREATE TABLE IF NOT EXISTS study_resources (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    material_id UUID REFERENCES materials(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    resource_type TEXT NOT NULL CHECK (resource_type IN ('summary', 'key_points', 'practice_questions')),
    content_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_resources_course ON study_resources(course_id);
CREATE INDEX IF NOT EXISTS idx_resources_material ON study_resources(material_id);

ALTER TABLE study_resources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "everyone_view_study_resources" ON study_resources
    FOR SELECT USING (true);
CREATE POLICY "service_role_study_resources" ON study_resources
    FOR ALL TO service_role USING (true) WITH CHECK (true);
