-- Migration: 20260813000015_ai_quizzes.sql
-- Stores quizzes generated by the AI from course materials, and student submissions.

CREATE TABLE IF NOT EXISTS generated_quizzes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    material_id UUID NOT NULL REFERENCES materials(id) ON DELETE CASCADE,
    quiz_data JSONB NOT NULL, -- { "objective": [...], "theory": [...] }
    generated_for_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quizzes_material ON generated_quizzes(material_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_date ON generated_quizzes(generated_for_date);

CREATE TABLE IF NOT EXISTS quiz_submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    quiz_id UUID NOT NULL REFERENCES generated_quizzes(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    answers JSONB NOT NULL,
    score NUMERIC NOT NULL,
    comprehension_level TEXT NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_submissions_student ON quiz_submissions(student_id);

ALTER TABLE generated_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "everyone_view_quizzes" ON generated_quizzes FOR SELECT USING (true);
CREATE POLICY "service_role_quizzes" ON generated_quizzes FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "students_view_own_submissions" ON quiz_submissions FOR SELECT USING (student_id = auth.uid());
CREATE POLICY "students_insert_own_submissions" ON quiz_submissions FOR INSERT WITH CHECK (student_id = auth.uid());
CREATE POLICY "service_role_submissions" ON quiz_submissions FOR ALL TO service_role USING (true) WITH CHECK (true);
